# Final 

## read train.csv into dataframe

```{r}
#install.packages("knitr")
library(knitr)
df <- read.csv("Titanic/train.csv",na.strings = "")

```

## convert Survived column and Pclass column to factors

```{r}
df$Survived<- as.factor(df$Survived)
df$Pclass<- as.factor(df$Pclass)
```

## remove from df : PassengerId, Name, Ticket, Cabin

```{r}
df <- df[,-c(1,4,9,11)]
```

## split into factors and numerics columns

```{r}
cols<- 1:dim(df)[2]
factors <- cols[sapply(df,is.factor)]
numerics <- cols[!sapply(df,is.factor)]
```


## We now tide the data two times: the first is for categorial data and the second for numeric data.

```{r}
#install.packages("tidyr")
library(tidyr)
df_tidy_factors<-gather(df[,factors],"feature","value",-1)
df_tidy_numerics<-gather(cbind(Survived=df[,1],df[,numerics]),"feature","value",-1)
```
```{r}
#install.packages("stringi")
library(ggplot2)
qplot(x=value,data=df_tidy_factors,fill=Survived) + facet_grid(~feature,scales="free")
```



```{r}
#install.packages("C50")
library(C50)
set.seed(123)
C50 <-C5.0(Survived ~., data=df)
```



```{r}
new_df <-read.csv('Titanic/test.csv',na.strings = "")
ids<- new_df$PassengerId
new_df$Pclass<- as.factor(new_df$Pclass)
new_df<- new_df[,-c(1,3,8,10)]
pred<- predict(C50,new_df)
```


```{r}
submit <- data.frame(PassengerId =ids, Survived = pred)
write.csv(submit, file = "naive.csv", row.names = FALSE)
```


